development:
  server: iam0.dwpbank.net
  user: fmwuser
  deploy_dir: /opt/fmw/config/deploy/imint/new

test:
  server: dwptoim1.dwpbank.net
  user: fmwuser
  deploy_dir: /opt/fmw/config/deploy/imint/new

production:
  server: dwppoim1.dwpbank.net
  user: fmwuser
  deploy_dir: /opt/fmw/config/deploy/imint/new
