development:
  server: iam0.dwpbank.net
  user: fmwuser
  deploy_dir: /opt/fmw/config/deploy/imint/new
  shellenv: . ~/.env/idm-deplenv.env
  properties: .wlst/imint.prop

test:
  server: dwptoim1
  user: fmwuser
  deploy_dir: /opt/fmw/config/deploy/imint/new
  shellenv: . ~/.env/idm-deplenv.env
  properties: .wlst/imint.prop

production:
  server: iam0
  user: fmwuser
  deploy_dir: /opt/fmw/config/deploy/imint/new
  shellenv: . ~/.env/idm-deplenv.env
  properties: .env/imint.prop
